const tag = document.getElementById("highlight");
const tags = document.getElementsByClassName("bolded");
const tagName = document.getElementsByTagName("li");
const tagCss = document.querySelector("#highlight");
const tagFirst = document.querySelector(".bolded");
const h1First = document.querySelector("h1");
const li = document.querySelector("li a.special");
const all = document.querySelectorAll("h1");
const all2 = document.querySelectorAll(".bolded");
console.log(tag);
console.dir(tag);
console.log(tags);
console.dir(tags);
console.log(tagName);
console.dir(tagName);
console.log(tagCss);
console.dir(tagCss);
console.log(tagFirst);
console.dir(tagFirst);
console.log(h1First);
console.dir(h1First);
console.log(li);
console.dir(li);
console.log(all);
console.dir(all);
console.log(all2);
console.dir(all2);
